import { BlockTypeDefinition } from './types';

export const BLOCK_CATEGORIES = {
  event: {
    title: 'Eventos',
    color: 'border-emerald-500/30 bg-emerald-50/50 dark:bg-emerald-950/20 text-emerald-700 dark:text-emerald-400',
  },
  activity: {
    title: 'Atividades',
    color: 'border-sky-500/30 bg-sky-50/50 dark:bg-sky-950/20 text-sky-700 dark:text-sky-400',
  },
  decision: {
    title: 'Decisões',
    color: 'border-amber-500/30 bg-amber-50/50 dark:bg-amber-950/20 text-amber-700 dark:text-amber-400',
  },
  auxiliary: {
    title: 'Elementos Auxiliares',
    color: 'border-purple-500/30 bg-purple-50/50 dark:bg-purple-950/20 text-purple-700 dark:text-purple-400',
  },
};

export const BLOCK_DEFINITIONS: BlockTypeDefinition[] = [
  // --- EVENTOS ---
  {
    type: 'start',
    category: 'event',
    title: 'Início',
    description: 'Início simples do processo',
    icon: 'Play',
    inputs: [],
    outputs: ['right', 'bottom'],
  },
  {
    type: 'start-message',
    category: 'event',
    title: 'Início por Mensagem',
    description: 'Disparado por uma mensagem, email ou notificação recebida',
    icon: 'Mail',
    inputs: [],
    outputs: ['right', 'bottom'],
  },
  {
    type: 'start-timer',
    category: 'event',
    title: 'Início por Prazo',
    description: 'Disparado em uma data, horário ou cronograma recorrente',
    icon: 'Clock',
    inputs: [],
    outputs: ['right', 'bottom'],
  },
  {
    type: 'end',
    category: 'event',
    title: 'Término',
    description: 'Finalização normal do processo',
    icon: 'Square',
    inputs: ['left', 'top'],
    outputs: [],
  },
  {
    type: 'end-message',
    category: 'event',
    title: 'Término por Mensagem',
    description: 'Finaliza o processo e dispara uma mensagem ou webhook externo',
    icon: 'Send',
    inputs: ['left', 'top'],
    outputs: [],
  },
  {
    type: 'intermediate',
    category: 'event',
    title: 'Evento Intermediário',
    description: 'Ocorre entre o início e o fim, gerando uma ação temporária',
    icon: 'AlertCircle',
    inputs: ['left', 'top', 'bottom'],
    outputs: ['right', 'bottom'],
  },
  {
    type: 'timer',
    category: 'event',
    title: 'Espera',
    description: 'Aguardar uma condição externa ou período determinado',
    icon: 'Hourglass',
    inputs: ['left', 'top'],
    outputs: ['right', 'bottom'],
  },

  // --- ATIVIDADES ---
  {
    type: 'task',
    category: 'activity',
    title: 'Tarefa',
    description: 'Uma unidade genérica de trabalho ou ação',
    icon: 'CheckSquare',
    inputs: ['left', 'top', 'bottom'],
    outputs: ['right', 'bottom', 'top'],
  },
  {
    type: 'task-manual',
    category: 'activity',
    title: 'Atividade Manual',
    description: 'Tarefa realizada fisicamente, sem uso de sistemas ou softwares',
    icon: 'Wrench',
    inputs: ['left', 'top', 'bottom'],
    outputs: ['right', 'bottom', 'top'],
  },
  {
    type: 'task-user',
    category: 'activity',
    title: 'Atividade de Usuário',
    description: 'Tarefa executada em um sistema por um operador humano',
    icon: 'User',
    inputs: ['left', 'top', 'bottom'],
    outputs: ['right', 'bottom', 'top'],
  },
  {
    type: 'task-auto',
    category: 'activity',
    title: 'Atividade Automática',
    description: 'Tarefa automatizada de sistema (script, API, bot)',
    icon: 'Cpu',
    inputs: ['left', 'top', 'bottom'],
    outputs: ['right', 'bottom', 'top'],
  },
  {
    type: 'document-send',
    category: 'activity',
    title: 'Envio de Documento',
    description: 'Envio físico ou digital de arquivos ou documentos',
    icon: 'UploadCloud',
    inputs: ['left', 'top', 'bottom'],
    outputs: ['right', 'bottom'],
  },
  {
    type: 'document-recv',
    category: 'activity',
    title: 'Recebimento de Documento',
    description: 'Recepção e validação de arquivos ou documentos',
    icon: 'DownloadCloud',
    inputs: ['left', 'top', 'bottom'],
    outputs: ['right', 'bottom'],
  },
  {
    type: 'analysis',
    category: 'activity',
    title: 'Análise',
    description: 'Avaliação técnica de informações ou solicitações',
    icon: 'BarChart2',
    inputs: ['left', 'top', 'bottom'],
    outputs: ['right', 'bottom'],
  },
  {
    type: 'approval',
    category: 'activity',
    title: 'Aprovação',
    description: 'Aprovação de solicitação por um gestor ou responsável',
    icon: 'CheckCircle',
    inputs: ['left', 'top', 'bottom'],
    outputs: ['right', 'bottom', 'top'],
  },
  {
    type: 'confer',
    category: 'activity',
    title: 'Conferência',
    description: 'Conferência detalhada ou auditoria de dados',
    icon: 'ClipboardCheck',
    inputs: ['left', 'top', 'bottom'],
    outputs: ['right', 'bottom'],
  },
  {
    type: 'sign',
    category: 'activity',
    title: 'Assinatura',
    description: 'Assinatura física ou eletrônica de documentos',
    icon: 'PenTool',
    inputs: ['left', 'top', 'bottom'],
    outputs: ['right', 'bottom'],
  },
  {
    type: 'notify',
    category: 'activity',
    title: 'Notificação',
    description: 'Disparar notificação (e-mail, SMS, WhatsApp) para interessados',
    icon: 'Bell',
    inputs: ['left', 'top', 'bottom'],
    outputs: ['right', 'bottom'],
  },
  {
    type: 'subprocess',
    category: 'activity',
    title: 'Subprocesso',
    description: 'Fluxo interno encapsulado que detalha uma etapa complexa',
    icon: 'Layers',
    inputs: ['left', 'top', 'bottom'],
    outputs: ['right', 'bottom', 'top'],
  },

  // --- DECISÕES ---
  {
    type: 'decision-exclusive',
    category: 'decision',
    title: 'Decisão Exclusiva',
    description: 'Desvia o fluxo para apenas um dos caminhos de saída (XOR)',
    icon: 'HelpCircle',
    inputs: ['left', 'top'],
    outputs: ['right', 'bottom', 'top'],
  },
  {
    type: 'decision-parallel',
    category: 'decision',
    title: 'Decisão Paralela',
    description: 'Ativa simultaneamente todos os caminhos de saída (AND)',
    icon: 'GitFork',
    inputs: ['left', 'top'],
    outputs: ['right', 'bottom', 'top'],
  },
  {
    type: 'decision-inclusive',
    category: 'decision',
    title: 'Decisão Inclusiva',
    description: 'Ativa um ou mais caminhos com base em condições avaliadas (OR)',
    icon: 'GitPullRequest',
    inputs: ['left', 'top'],
    outputs: ['right', 'bottom', 'top'],
  },
  {
    type: 'condition-simple',
    category: 'decision',
    title: 'Condição Simples',
    description: 'Avaliação de uma regra básica de negócio',
    icon: 'Split',
    inputs: ['left', 'top'],
    outputs: ['right', 'bottom'],
  },
  {
    type: 'approval-rejection',
    category: 'decision',
    title: 'Aprovação / Rejeição',
    description: 'Bifurcação simples entre Aprovado (segue) e Rejeitado (retorna)',
    icon: 'ThumbsUp',
    inputs: ['left', 'top'],
    outputs: ['right', 'bottom', 'top'],
  },
  {
    type: 'yes-no',
    category: 'decision',
    title: 'Sim ou Não',
    description: 'Escolha binária rápida para desvio de fluxo',
    icon: 'ToggleLeft',
    inputs: ['left', 'top'],
    outputs: ['right', 'bottom'],
  },

  // --- AUXILIARES ---
  {
    type: 'doc',
    category: 'auxiliary',
    title: 'Documento',
    description: 'Documento gerado ou exigido nesta fase',
    icon: 'FileText',
    inputs: ['left', 'top', 'bottom', 'right'],
    outputs: ['left', 'top', 'bottom', 'right'],
  },
  {
    type: 'form',
    category: 'auxiliary',
    title: 'Formulário',
    description: 'Formulário eletrônico preenchido pelo usuário',
    icon: 'FileSpreadsheet',
    inputs: ['left', 'top', 'bottom', 'right'],
    outputs: ['left', 'top', 'bottom', 'right'],
  },
  {
    type: 'note',
    category: 'auxiliary',
    title: 'Observação',
    description: 'Nota de texto ou esclarecimento associado',
    icon: 'MessageSquare',
    inputs: ['left', 'top', 'bottom', 'right'],
    outputs: ['left', 'top', 'bottom', 'right'],
  },
  {
    type: 'external-system',
    category: 'auxiliary',
    title: 'Sistema Externo',
    description: 'Integração ou consulta a um software parceiro ou externo',
    icon: 'Globe',
    inputs: ['left', 'top', 'bottom', 'right'],
    outputs: ['left', 'top', 'bottom', 'right'],
  },
  {
    type: 'database',
    category: 'auxiliary',
    title: 'Banco de Dados',
    description: 'Leitura ou escrita em repositório de dados persistente',
    icon: 'Database',
    inputs: ['left', 'top', 'bottom', 'right'],
    outputs: ['left', 'top', 'bottom', 'right'],
  },
  {
    type: 'link',
    category: 'auxiliary',
    title: 'Link Externo',
    description: 'Atalho para página web externa, normativos ou legislação',
    icon: 'ExternalLink',
    inputs: ['left', 'top', 'bottom', 'right'],
    outputs: ['left', 'top', 'bottom', 'right'],
  },
];

export const LANE_COLORS = [
  { name: 'Azul Slate', value: '#38bdf8', class: 'bg-slate-100 border-slate-300 dark:bg-slate-900 dark:border-slate-800' },
  { name: 'Esmeralda', value: '#10b981', class: 'bg-emerald-50 border-emerald-200 dark:bg-emerald-950/20 dark:border-emerald-900' },
  { name: 'Indigo', value: '#6366f1', class: 'bg-indigo-50 border-indigo-200 dark:bg-indigo-950/20 dark:border-indigo-900' },
  { name: 'Amber', value: '#f59e0b', class: 'bg-amber-50 border-amber-200 dark:bg-amber-950/20 dark:border-amber-900' },
  { name: 'Violeta', value: '#8b5cf6', class: 'bg-violet-50 border-violet-200 dark:bg-violet-950/20 dark:border-violet-900' },
  { name: 'Crimson', value: '#f43f5e', class: 'bg-rose-50 border-rose-200 dark:bg-rose-950/20 dark:border-rose-900' },
];

export const GRID_CELL_SIZE = 80; // Size of a square grid cell in pixels
export const LANE_DEFAULT_HEIGHT = 4; // default height in grid cells (4 * 80 = 320px)
