import { ProcessModel } from './types';

export const TEMPLATE_PROCESSES: ProcessModel[] = [
  // --- TEMPLATE 1: CONTRATAÇÃO DE PESSOAL ---
  {
    id: 'template-hiring',
    name: 'Processo de Contratação de Pessoal',
    description: 'Fluxo estruturado para solicitação de vaga, triagem pelo RH, aprovação financeira e finalização da contratação.',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    lanes: [
      {
        id: 'lane-hiring-manager',
        name: 'Gestor Solicitante',
        description: 'Responsável por iniciar a vaga e avaliar candidatos',
        color: '#6366f1',
        height: 3,
      },
      {
        id: 'lane-hiring-hr',
        name: 'Recursos Humanos',
        description: 'Responsável pela triagem, entrevistas e trâmites de contratação',
        color: '#38bdf8',
        height: 3,
      },
      {
        id: 'lane-hiring-fin',
        name: 'Diretoria Financeira',
        description: 'Aprova o orçamento e o teto salarial da vaga',
        color: '#10b981',
        height: 2,
      },
    ],
    nodes: [
      {
        id: 'node-h1',
        type: 'start',
        title: 'Abertura de Vaga',
        description: 'Gestor identifica necessidade de contratação',
        laneId: 'lane-hiring-manager',
        row: 1,
        column: 0,
        inputs: [],
        outputs: [{ id: 'right', type: 'output' }],
        responsible: 'Gestor da Área',
        estimatedDuration: 'Imediato',
        priority: 'Média',
      },
      {
        id: 'node-h2',
        type: 'form',
        title: 'Preencher Requisição',
        description: 'Preenchimento do formulário com perfil, salário e justificativa',
        laneId: 'lane-hiring-manager',
        row: 1,
        column: 1,
        inputs: [{ id: 'left', type: 'input' }],
        outputs: [{ id: 'right', type: 'output' }],
        responsible: 'Gestor da Área',
        estimatedDuration: '1 hora',
        priority: 'Média',
        systems: ['ERP Corporativo', 'Intranet'],
        inputDocuments: ['Ficha de Perfil'],
        outputDocuments: ['Requisição de Vaga (PDF)'],
      },
      {
        id: 'node-h3',
        type: 'task-user',
        title: 'Triagem de Perfil',
        description: 'Validação inicial dos requisitos mínimos da vaga',
        laneId: 'lane-hiring-hr',
        row: 1,
        column: 2,
        inputs: [{ id: 'left', type: 'input' }, { id: 'top', type: 'input' }],
        outputs: [{ id: 'right', type: 'output' }],
        responsible: 'Analista de R&S',
        estimatedDuration: '1 dia',
        priority: 'Média',
        systems: ['ATS - Gupy'],
      },
      {
        id: 'node-h4',
        type: 'decision-exclusive',
        title: 'Requisitos Válidos?',
        description: 'O perfil solicitado está de acordo com as normas da empresa?',
        laneId: 'lane-hiring-hr',
        row: 1,
        column: 3,
        inputs: [{ id: 'left', type: 'input' }],
        outputs: [
          { id: 'top', type: 'output' },
          { id: 'right', type: 'output' },
        ],
      },
      {
        id: 'node-h5',
        type: 'task',
        title: 'Ajustar Perfil',
        description: 'RH entra em contato para alinhar especificações da vaga',
        laneId: 'lane-hiring-manager',
        row: 2,
        column: 2,
        inputs: [{ id: 'right', type: 'input' }],
        outputs: [{ id: 'bottom', type: 'output' }],
        responsible: 'Gestor + RH',
        estimatedDuration: '4 horas',
        priority: 'Baixa',
      },
      {
        id: 'node-h6',
        type: 'approval',
        title: 'Validar Orçamento',
        description: 'Diretoria Financeira confere orçamento disponível',
        laneId: 'lane-hiring-fin',
        row: 0,
        column: 4,
        inputs: [{ id: 'left', type: 'input' }],
        outputs: [{ id: 'right', type: 'output' }],
        responsible: 'Diretor Financeiro',
        estimatedDuration: '2 dias',
        priority: 'Alta',
        systems: ['SIAF - Finanças'],
      },
      {
        id: 'node-h7',
        type: 'yes-no',
        title: 'Aprovado?',
        description: 'Orçamento da vaga foi autorizado?',
        laneId: 'lane-hiring-fin',
        row: 0,
        column: 5,
        inputs: [{ id: 'left', type: 'input' }],
        outputs: [
          { id: 'top', type: 'output' },
          { id: 'right', type: 'output' },
        ],
      },
      {
        id: 'node-h8',
        type: 'notify',
        title: 'Notificar Recusa',
        description: 'Informa ao gestor sobre a reprovação da vaga',
        laneId: 'lane-hiring-manager',
        row: 2,
        column: 5,
        inputs: [{ id: 'bottom', type: 'input' }],
        outputs: [{ id: 'right', type: 'output' }],
        responsible: 'E-mail Automático',
        estimatedDuration: '5 minutos',
        priority: 'Baixa',
      },
      {
        id: 'node-h9',
        type: 'end-message',
        title: 'Fim - Reprovada',
        description: 'Processo encerrado por falta de orçamento',
        laneId: 'lane-hiring-manager',
        row: 2,
        column: 6,
        inputs: [{ id: 'left', type: 'input' }],
        outputs: [],
      },
      {
        id: 'node-h10',
        type: 'task-auto',
        title: 'Publicar Vaga',
        description: 'Disparar divulgação nos canais oficiais',
        laneId: 'lane-hiring-hr',
        row: 1,
        column: 6,
        inputs: [{ id: 'left', type: 'input' }],
        outputs: [{ id: 'right', type: 'output' }],
        responsible: 'Robô ATS',
        estimatedDuration: '30 minutos',
        systems: ['LinkedIn', 'ATS - Gupy'],
      },
      {
        id: 'node-h11',
        type: 'task-user',
        title: 'Entrevistas e Testes',
        description: 'Dinâmicas de grupo, testes técnicos e avaliação psicológica',
        laneId: 'lane-hiring-hr',
        row: 1,
        column: 7,
        inputs: [{ id: 'left', type: 'input' }],
        outputs: [{ id: 'top', type: 'output' }],
        responsible: 'Recrutador / Business Partner',
        estimatedDuration: '5 dias',
        priority: 'Média',
        outputDocuments: ['Laudo de Avaliação'],
      },
      {
        id: 'node-h12',
        type: 'sign',
        title: 'Aprovar Candidato',
        description: 'Avaliação final e assinatura de aprovação pelo gestor',
        laneId: 'lane-hiring-manager',
        row: 1,
        column: 8,
        inputs: [{ id: 'bottom', type: 'input' }],
        outputs: [{ id: 'right', type: 'output' }],
        responsible: 'Gestor da Área',
        estimatedDuration: '1 dia',
        priority: 'Alta',
        inputDocuments: ['Laudo de Avaliação'],
        outputDocuments: ['Proposta de Trabalho Assinada'],
      },
      {
        id: 'node-h13',
        type: 'end',
        title: 'Fim - Contratado',
        description: 'Candidato aceita proposta e inicia onboarding',
        laneId: 'lane-hiring-hr',
        row: 1,
        column: 9,
        inputs: [{ id: 'left', type: 'input' }],
        outputs: [],
      },
    ],
    connections: [
      {
        id: 'conn-h1',
        sourceNodeId: 'node-h1',
        sourceConnectorId: 'right',
        targetNodeId: 'node-h2',
        targetConnectorId: 'left',
      },
      {
        id: 'conn-h2',
        sourceNodeId: 'node-h2',
        sourceConnectorId: 'right',
        targetNodeId: 'node-h3',
        targetConnectorId: 'left',
      },
      {
        id: 'conn-h3',
        sourceNodeId: 'node-h3',
        sourceConnectorId: 'right',
        targetNodeId: 'node-h4',
        targetConnectorId: 'left',
      },
      {
        id: 'conn-h4',
        sourceNodeId: 'node-h4',
        sourceConnectorId: 'top',
        targetNodeId: 'node-h5',
        targetConnectorId: 'right',
        label: 'Não',
        condition: 'Ajustes necessários',
      },
      {
        id: 'conn-h5',
        sourceNodeId: 'node-h5',
        sourceConnectorId: 'bottom',
        targetNodeId: 'node-h3',
        targetConnectorId: 'top',
      },
      {
        id: 'conn-h6',
        sourceNodeId: 'node-h4',
        sourceConnectorId: 'right',
        targetNodeId: 'node-h6',
        targetConnectorId: 'left',
        label: 'Sim',
        condition: 'Requisitos OK',
      },
      {
        id: 'conn-h7',
        sourceNodeId: 'node-h6',
        sourceConnectorId: 'right',
        targetNodeId: 'node-h7',
        targetConnectorId: 'left',
      },
      {
        id: 'conn-h8',
        sourceNodeId: 'node-h7',
        sourceConnectorId: 'top',
        targetNodeId: 'node-h8',
        targetConnectorId: 'bottom',
        label: 'Não',
        condition: 'Sem Verba',
      },
      {
        id: 'conn-h9',
        sourceNodeId: 'node-h8',
        sourceConnectorId: 'right',
        targetNodeId: 'node-h9',
        targetConnectorId: 'left',
      },
      {
        id: 'conn-h10',
        sourceNodeId: 'node-h7',
        sourceConnectorId: 'right',
        targetNodeId: 'node-h10',
        targetConnectorId: 'left',
        label: 'Sim',
        condition: 'Aprovado',
      },
      {
        id: 'conn-h11',
        sourceNodeId: 'node-h10',
        sourceConnectorId: 'right',
        targetNodeId: 'node-h11',
        targetConnectorId: 'left',
      },
      {
        id: 'conn-h12',
        sourceNodeId: 'node-h11',
        sourceConnectorId: 'top',
        targetNodeId: 'node-h12',
        targetConnectorId: 'bottom',
      },
      {
        id: 'conn-h13',
        sourceNodeId: 'node-h12',
        sourceConnectorId: 'right',
        targetNodeId: 'node-h13',
        targetConnectorId: 'left',
      },
    ],
  },

  // --- TEMPLATE 2: ATENDIMENTO AO CIDADÃO / REQUERIMENTO ---
  {
    id: 'template-citizen',
    name: 'Análise de Requerimento de Cidadão',
    description: 'Protocolo de solicitação de serviço público por cidadão, com triagem na recepção e análise de deferimento por técnico.',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    lanes: [
      {
        id: 'lane-cit-user',
        name: 'Cidadão / Requerente',
        description: 'Usuário externo que solicita o serviço e acompanha o trâmite',
        color: '#f59e0b',
        height: 2,
      },
      {
        id: 'lane-cit-front',
        name: 'Protocolo / Triagem',
        description: 'Setor de recepção responsável por receber e triar documentos',
        color: '#8b5cf6',
        height: 3,
      },
      {
        id: 'lane-cit-tech',
        name: 'Setor Técnico Finalístico',
        description: 'Setor especializado que realiza a perícia, vistoria ou análise de mérito',
        color: '#38bdf8',
        height: 3,
      },
    ],
    nodes: [
      {
        id: 'node-c1',
        type: 'start-message',
        title: 'Criar Protocolo',
        description: 'Cidadão inicia requerimento na plataforma online',
        laneId: 'lane-cit-user',
        row: 1,
        column: 0,
        inputs: [],
        outputs: [{ id: 'right', type: 'output' }],
        responsible: 'Cidadão',
        estimatedDuration: '30 minutos',
        priority: 'Média',
      },
      {
        id: 'node-c2',
        type: 'form',
        title: 'Preencher Dados',
        description: 'Digitar dados cadastrais e selecionar o tipo de serviço solicitado',
        laneId: 'lane-cit-user',
        row: 1,
        column: 1,
        inputs: [{ id: 'left', type: 'input' }, { id: 'top', type: 'input' }],
        outputs: [{ id: 'right', type: 'output' }],
        responsible: 'Cidadão',
        estimatedDuration: '20 minutos',
        systems: ['Portal do Cidadão'],
      },
      {
        id: 'node-c3',
        type: 'document-send',
        title: 'Enviar Anexos',
        description: 'Enviar RG, comprovante de residência e plantas se aplicável',
        laneId: 'lane-cit-user',
        row: 1,
        column: 2,
        inputs: [{ id: 'left', type: 'input' }],
        outputs: [{ id: 'right', type: 'output' }],
        responsible: 'Cidadão',
        estimatedDuration: '10 minutos',
        outputDocuments: ['Documentos Digitalizados'],
      },
      {
        id: 'node-c4',
        type: 'confer',
        title: 'Validar Documentos',
        description: 'Recepção verifica nitidez, validade e completude de anexos',
        laneId: 'lane-cit-front',
        row: 1,
        column: 3,
        inputs: [{ id: 'left', type: 'input' }],
        outputs: [{ id: 'right', type: 'output' }],
        responsible: 'Atendente de Protocolo',
        estimatedDuration: '4 horas',
        priority: 'Alta',
        systems: ['SEI - Sistema Eletrônico de Informações'],
      },
      {
        id: 'node-c5',
        type: 'decision-exclusive',
        title: 'Tudo Correto?',
        description: 'Os documentos atendem aos critérios de admissibilidade?',
        laneId: 'lane-cit-front',
        row: 1,
        column: 4,
        inputs: [{ id: 'left', type: 'input' }],
        outputs: [
          { id: 'top', type: 'output' },
          { id: 'right', type: 'output' },
        ],
      },
      {
        id: 'node-c6',
        type: 'notify',
        title: 'Solicitar Correção',
        description: 'Notifica o cidadão via sistema e e-mail sobre exigências de correção',
        laneId: 'lane-cit-front',
        row: 2,
        column: 2,
        inputs: [{ id: 'right', type: 'input' }],
        outputs: [{ id: 'top', type: 'output' }],
        responsible: 'Atendente / Notificação Automática',
        estimatedDuration: '10 minutos',
      },
      {
        id: 'node-c7',
        type: 'analysis',
        title: 'Análise de Mérito',
        description: 'Técnico avalia conformidade legal e técnica do pedido',
        laneId: 'lane-cit-tech',
        row: 1,
        column: 5,
        inputs: [{ id: 'left', type: 'input' }],
        outputs: [{ id: 'right', type: 'output' }],
        responsible: 'Analista de Negócios / Técnico',
        estimatedDuration: '3 dias',
        priority: 'Média',
        systems: ['SEI / Geoprocessamento'],
      },
      {
        id: 'node-c8',
        type: 'approval-rejection',
        title: 'Deferimento',
        description: 'Aprovação técnica final',
        laneId: 'lane-cit-tech',
        row: 1,
        column: 6,
        inputs: [{ id: 'left', type: 'input' }],
        outputs: [
          { id: 'right', type: 'output' },
          { id: 'top', type: 'output' },
        ],
      },
      {
        id: 'node-c9',
        type: 'notify',
        title: 'Emitir Deferimento',
        description: 'Gera certidão ou licença deferida e avisa cidadão',
        laneId: 'lane-cit-front',
        row: 1,
        column: 7,
        inputs: [{ id: 'left', type: 'input' }],
        outputs: [{ id: 'right', type: 'output' }],
        responsible: 'Robô do Protocolo',
        estimatedDuration: '15 minutos',
        outputDocuments: ['Certidão de Deferimento'],
      },
      {
        id: 'node-c10',
        type: 'notify',
        title: 'Emitir Indeferimento',
        description: 'Gera termo de indeferimento fundamentado e avisa cidadão',
        laneId: 'lane-cit-front',
        row: 2,
        column: 7,
        inputs: [{ id: 'bottom', type: 'input' }],
        outputs: [{ id: 'right', type: 'output' }],
        responsible: 'Atendente de Protocolo',
        estimatedDuration: '1 hora',
        outputDocuments: ['Termo de Indeferimento'],
      },
      {
        id: 'node-c11',
        type: 'end',
        title: 'Processo Concluído',
        description: 'Serviço público finalizado e entregue ao cidadão',
        laneId: 'lane-cit-user',
        row: 1,
        column: 8,
        inputs: [{ id: 'left', type: 'input' }],
        outputs: [],
      },
    ],
    connections: [
      {
        id: 'conn-c1',
        sourceNodeId: 'node-c1',
        sourceConnectorId: 'right',
        targetNodeId: 'node-c2',
        targetConnectorId: 'left',
      },
      {
        id: 'conn-c2',
        sourceNodeId: 'node-c2',
        sourceConnectorId: 'right',
        targetNodeId: 'node-c3',
        targetConnectorId: 'left',
      },
      {
        id: 'conn-c3',
        sourceNodeId: 'node-c3',
        sourceConnectorId: 'right',
        targetNodeId: 'node-c4',
        targetConnectorId: 'left',
      },
      {
        id: 'conn-c4',
        sourceNodeId: 'node-c4',
        sourceConnectorId: 'right',
        targetNodeId: 'node-c5',
        targetConnectorId: 'left',
      },
      {
        id: 'conn-c5',
        sourceNodeId: 'node-c5',
        sourceConnectorId: 'top',
        targetNodeId: 'node-c6',
        targetConnectorId: 'right',
        label: 'Incompleto',
        condition: 'Faltam anexos',
      },
      {
        id: 'conn-c6',
        sourceNodeId: 'node-c6',
        sourceConnectorId: 'top',
        targetNodeId: 'node-c2',
        targetConnectorId: 'top',
      },
      {
        id: 'conn-c7',
        sourceNodeId: 'node-c5',
        sourceConnectorId: 'right',
        targetNodeId: 'node-c7',
        targetConnectorId: 'left',
        label: 'Correto',
        condition: 'Documentos válidos',
      },
      {
        id: 'conn-c8',
        sourceNodeId: 'node-c7',
        sourceConnectorId: 'right',
        targetNodeId: 'node-c8',
        targetConnectorId: 'left',
      },
      {
        id: 'conn-c9',
        sourceNodeId: 'node-c8',
        sourceConnectorId: 'right',
        targetNodeId: 'node-c9',
        targetConnectorId: 'left',
        label: 'Deferido',
        condition: 'Critérios atendidos',
      },
      {
        id: 'conn-c10',
        sourceNodeId: 'node-c8',
        sourceConnectorId: 'top',
        targetNodeId: 'node-c10',
        targetConnectorId: 'bottom',
        label: 'Indeferido',
        condition: 'Fora da legalidade',
      },
      {
        id: 'conn-c11',
        sourceNodeId: 'node-c9',
        sourceConnectorId: 'right',
        targetNodeId: 'node-c11',
        targetConnectorId: 'left',
      },
      {
        id: 'conn-c12',
        sourceNodeId: 'node-c10',
        sourceConnectorId: 'right',
        targetNodeId: 'node-c11',
        targetConnectorId: 'left',
      },
    ],
  },

  // --- TEMPLATE 3: FLUXO DE COMPRAS (PROCUREMENT) ---
  {
    id: 'template-procurement',
    name: 'Fluxo de Compras e Suprimentos',
    description: 'Processo padrão de aquisição corporativa, desde a identificação da necessidade, cotação comercial e emissão de pedido.',
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    lanes: [
      {
        id: 'lane-proc-dept',
        name: 'Setor Solicitante',
        description: 'Área da empresa que necessita do produto ou serviço',
        color: '#6366f1',
        height: 2,
      },
      {
        id: 'lane-proc-buy',
        name: 'Departamento de Compras',
        description: 'Setor que cota preços e negocia com fornecedores',
        color: '#38bdf8',
        height: 3,
      },
      {
        id: 'lane-proc-dir',
        name: 'Diretoria Executiva',
        description: 'Aprova despesas financeiras fora da alçada padrão',
        color: '#f43f5e',
        height: 2,
      },
    ],
    nodes: [
      {
        id: 'node-p1',
        type: 'start',
        title: 'Identificar Necessidade',
        description: 'Identificação de falta de suprimento ou insumo',
        laneId: 'lane-proc-dept',
        row: 1,
        column: 0,
        inputs: [],
        outputs: [{ id: 'right', type: 'output' }],
        responsible: 'Colaborador',
        estimatedDuration: 'Imediato',
        priority: 'Baixa',
      },
      {
        id: 'node-p2',
        type: 'form',
        title: 'Criar Requisição',
        description: 'Cadastro de especificações e quantidades exigidas',
        laneId: 'lane-proc-dept',
        row: 1,
        column: 1,
        inputs: [{ id: 'left', type: 'input' }],
        outputs: [{ id: 'right', type: 'output' }],
        responsible: 'Gestor da Área',
        estimatedDuration: '1 hora',
        systems: ['ERP - Módulo de Compras'],
        outputDocuments: ['Requisição de Compra'],
      },
      {
        id: 'node-p3',
        type: 'task-user',
        title: 'Cotar Preços',
        description: 'Pesquisar e solicitar cotações de no mínimo 3 fornecedores',
        laneId: 'lane-proc-buy',
        row: 1,
        column: 2,
        inputs: [{ id: 'left', type: 'input' }],
        outputs: [{ id: 'right', type: 'output' }],
        responsible: 'Comprador',
        estimatedDuration: '2 dias',
        priority: 'Média',
        systems: ['E-mail', 'Portal de Fornecedores'],
        outputDocuments: ['Planilha de Cotações'],
      },
      {
        id: 'node-p4',
        type: 'analysis',
        title: 'Mapa de Coletas',
        description: 'Elaborar mapa comparativo de preços e prazos de entrega',
        laneId: 'lane-proc-buy',
        row: 1,
        column: 3,
        inputs: [{ id: 'left', type: 'input' }],
        outputs: [{ id: 'right', type: 'output' }],
        responsible: 'Comprador',
        estimatedDuration: '4 horas',
        inputDocuments: ['Planilha de Cotações'],
        outputDocuments: ['Mapa de Coleta de Preços (PDF)'],
      },
      {
        id: 'node-p5',
        type: 'condition-simple',
        title: 'Valor > R$ 10.000?',
        description: 'Determina a alçada de aprovação de acordo com o custo',
        laneId: 'lane-proc-buy',
        row: 1,
        column: 4,
        inputs: [{ id: 'left', type: 'input' }],
        outputs: [
          { id: 'top', type: 'output' },
          { id: 'right', type: 'output' },
        ],
      },
      {
        id: 'node-p6',
        type: 'approval',
        title: 'Aprovar Compra',
        description: 'Diretoria autoriza desembolso para valores altos',
        laneId: 'lane-proc-dir',
        row: 0,
        column: 5,
        inputs: [{ id: 'left', type: 'input' }],
        outputs: [{ id: 'right', type: 'output' }],
        responsible: 'Diretor Administrativo',
        estimatedDuration: '1 dia',
        priority: 'Alta',
        inputDocuments: ['Mapa de Coleta de Preços (PDF)'],
      },
      {
        id: 'node-p7',
        type: 'task-auto',
        title: 'Gerar Pedido',
        description: 'Emite o pedido de compra para o fornecedor vencedor',
        laneId: 'lane-proc-buy',
        row: 1,
        column: 6,
        inputs: [{ id: 'left', type: 'input' }, { id: 'top', type: 'input' }],
        outputs: [{ id: 'right', type: 'output' }],
        responsible: 'ERP Automático',
        estimatedDuration: '5 minutos',
        systems: ['ERP Corporativo'],
        outputDocuments: ['Pedido de Compra'],
      },
      {
        id: 'node-p8',
        type: 'end',
        title: 'Fim - Pedido Enviado',
        description: 'Pedido emitido e enviado ao fornecedor',
        laneId: 'lane-proc-dept',
        row: 1,
        column: 7,
        inputs: [{ id: 'left', type: 'input' }],
        outputs: [],
      },
    ],
    connections: [
      {
        id: 'conn-p1',
        sourceNodeId: 'node-p1',
        sourceConnectorId: 'right',
        targetNodeId: 'node-p2',
        targetConnectorId: 'left',
      },
      {
        id: 'conn-p2',
        sourceNodeId: 'node-p2',
        sourceConnectorId: 'right',
        targetNodeId: 'node-p3',
        targetConnectorId: 'left',
      },
      {
        id: 'conn-p3',
        sourceNodeId: 'node-p3',
        sourceConnectorId: 'right',
        targetNodeId: 'node-p4',
        targetConnectorId: 'left',
      },
      {
        id: 'conn-p4',
        sourceNodeId: 'node-p4',
        sourceConnectorId: 'right',
        targetNodeId: 'node-p5',
        targetConnectorId: 'left',
      },
      {
        id: 'conn-p5',
        sourceNodeId: 'node-p5',
        sourceConnectorId: 'top',
        targetNodeId: 'node-p6',
        targetConnectorId: 'left',
        label: 'Sim',
        condition: 'Custo Elevado',
      },
      {
        id: 'conn-p6',
        sourceNodeId: 'node-p5',
        sourceConnectorId: 'right',
        targetNodeId: 'node-p7',
        targetConnectorId: 'left',
        label: 'Não',
        condition: 'Compra Direta',
      },
      {
        id: 'conn-p7',
        sourceNodeId: 'node-p6',
        sourceConnectorId: 'right',
        targetNodeId: 'node-p7',
        targetConnectorId: 'top',
      },
      {
        id: 'conn-p8',
        sourceNodeId: 'node-p7',
        sourceConnectorId: 'right',
        targetNodeId: 'node-p8',
        targetConnectorId: 'left',
      },
    ],
  },
];
